services:
  - type: web
    name: seismic-log
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker seismic_api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
