services:
  - type: web
    name: genesis-seismic-log
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker seismic_api:app
    envVars:
      - key: PORT
        value: 8003
