services:
  - type: web
    name: simple-seismic-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 simple_seismic_server.py
    envVars:
      - key: PORT
        sync: false
